# SPDX-License-Identifier: Apache-2.0
# CubeSandbox Android workload image for x86_64 (ReDroid AOSP 16).

FROM redroid/redroid:16.0.0_64only-latest

LABEL org.opencontainers.image.title="CubeSandbox Android Sandbox (ReDroid AOSP 16)"
LABEL org.opencontainers.image.description="ReDroid Android 16 workload for CubeVM + cube-agent on x86_64"
LABEL org.opencontainers.image.vendor="Tencent Cloud CubeSandbox"
LABEL org.cubesandbox.sandbox.id="sandbox-android-x86-amd64"
LABEL org.cubesandbox.sandbox.category="android"
LABEL org.cubesandbox.sandbox.platform="x86-amd64"
LABEL org.cubesandbox.android.version="16"
LABEL org.cubesandbox.android.engine="redroid"
LABEL org.cubesandbox.instance_type="android"
LABEL org.cubesandbox.runtime_model="cubevm-redroid"

ENV CUBESANDBOX_REDROID_WIDTH=1080
ENV CUBESANDBOX_REDROID_HEIGHT=1920
ENV CUBESANDBOX_REDROID_DPI=480
ENV CUBESANDBOX_REDROID_GPU_MODE=guest
